language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - verilator
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev

install:
    # install conda for py 3.7
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
    - export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n test-env python=3.7
    - source activate test-env
    - conda install pip
    # End install conda
    - wget https://raw.githubusercontent.com/phanrahan/magma/master/.travis/install_coreir.sh
    - source install_coreir.sh

    - pip install pytest-cov pytest-pep8
    - pip install magma-lang mantle

script:
    - pytest --cov magma_tutorial --pep8 magma_tutorial -v --cov-report term-missing tests
